FROM ubuntu:22.04

RUN apt-get update && \
  apt-get install -y apt-utils git curl nano lsb-release python3 sudo wget net-tools iputils-ping tcpdump ethtool iperf iproute2 build-essential file vim

#COPY setup.sh .
#RUN chmod +x setup.sh

#COPY run_endpoint.sh .
#RUN chmod +x run_endpoint.sh

#RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x wait-for-it.sh

#ENTRYPOINT [ "/run_endpoint.sh" ]
